### ISSUE TITLE
Gulp Build Error

### ISSUE THREAD

**Issue by JustinWayneOlson** [SFII/educationcu#5]
Branch justin_rethink_test

var SubComp = React.createClass({
     render: function () {
      return (
           <p>{this.props.question}</p>
           {this.props.responses.map(function(response) {
              return <input type="radio" name="sex">{response}</input>;
           })}
           ) 
        }
     })

Error:
SyntaxError: /home/olsojus/Documents/educationcu/src/components/main/main.js: Unexpected token (8:8)
   6 |     return (
   7 |         <p>{this.props.question}</p>

>  8 |         {this.props.responses.map(function(response) {
>      |         ^
>    9 |            return <input type="radio" name="sex">{response}</input>;
>   10 |          })}
>   11 |         )
>     at Parser.pp.raise (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
>     at Parser.pp.unexpected (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
>     at Parser.pp.expect (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:76:33)
>     at Parser.pp.parseParenAndDistinguishExpression (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:466:12)
>     at Parser.parseParenAndDistinguishExpression (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:939:26)
>     at Parser.pp.parseExprAtom (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:378:19)
>     at Parser.parseExprAtom (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
>     at Parser.pp.parseExprSubscripts (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:236:19)
>     at Parser.pp.parseMaybeUnary (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:217:19)
>     at Parser.pp.parseExprOps (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:163:19)
>     at Parser.pp.parseMaybeConditional (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:145:19)
>     at Parser.pp.parseMaybeAssign (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:112:19)
>     at Parser.pp.parseExpression (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:79:19)
>     at Parser.pp.parseReturnStatement (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:287:26)
>     at Parser.pp.parseStatement (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:89:19)
>     at Parser.parseStatement (/home/olsojus/Documents/educationcu/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:621:22)

**Comment by peymanmortazavi** [comment]
It's because you have an invalid syntax here:

```
return (
    <p>{this.props.question}</p>
    {this.props.responses.map(function(response) {
       return <input type="radio" name="sex">{response}</input>;
     })}
    )
```

You can only have one element as root.

Try this:

<div>
        <p>{this.props.question}</p>
        {this.props.responses.map(function(response) {
           return <input type="radio" name="sex">{response}</input>;
         })}
</div>

**Comment by peymanmortazavi** [comment]
`return (
    <div>
    <p>{this.props.question}</p>
    {this.props.responses.map(function(response) {
       return <input type="radio" name="sex">{response}</input>;
     })}
</div>
    )`

**Comment by peymanmortazavi** [comment]
Just wrap it in a _div_ element

**Comment by JustinWayneOlson** [comment]
Wow. Michael and I stared at that for an hour. Thanks it works.
Justin

**Comment by peymanmortazavi** [comment]
Sweet!
